### ISSUE TITLE
Group balance based on skill, knowledge, etc.

### ISSUE THREAD

**Issue by thomastthai** [islemaster/good-enough-golfers#14]
An enhancement to consider is a `balanced` Boolean flag or whatever variable name to group people so the groups would be more balanced based on a rating (1 to 5) for each person. This rating could be based on skills, knowledge, etc.  

For example, in sports, we want the teams to be more balanced based on skills instead of all the best players being on the same team. 

Another example is for a classroom project, we want the more knowledgeable students and less knowledgeable students for that particular topic to spread across different groups.

Their ratings (1-5) could be to the end of their names separated by a space or use a regex pattern for the format.

**Comment by islemaster** [comment]
Thanks! This is a neat idea but it's beyond the scope of what I'd like this tool to do. That said, it's MIT-licensed so you or anyone else could always fork the repo and add that feature yourselves!
