### ISSUE TITLE
Add installation instruction to README.md

### ISSUE THREAD

**Issue by thomastthai** [islemaster/good-enough-golfers#15]
To assist non-programmers and non-developers, an Installation section in the `README.md` file would be helpful to let them know they need to set up a simple local web server to fully run `index.html` and the associated Javascript files.

Some users may try to load the `index.hml` file into a browser and expect it to work. They will get a page display but the associated Javascript files won't load because of a error like this:

```
Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/Users/{username}{/some-folder}/good-enough-golfers/lib/worker.js' cannot be accessed from origin 'null'.
    at file:///C:/Users/thomas/programming/JavaScript/good-enough-golfers/index.js:63:18
```

CORS won't allow access to the associated Javascript files from `index.html` using the `file://` URL schema. Therefore, at least a simple local web server is needed to access them via `http://`.

## nodejs Web Server

```
npm install http-server -g
cd good-enough-golfers
http-server
```

Then click on one of the displayed URLs in the terminal or copy and paste the URL into a browser and press ENTER.

## Python Web Server

```
cd good-enough-golfers
python3 -m http.server --port 8000
```

Then enter `http://127.0.0.1:8000/index.html` into the browser address bar and press ENTER.

**Comment by islemaster** [comment]
Good point! There's a `start` script for exactly this purpose in `package.json`. I've updated the README to point readers to this in https://github.com/islemaster/good-enough-golfers/commit/6dd516cd53f455dbc275b2f0d342e578ab397941
